-- 코드를 입력하세요
SELECT RI.REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, ROUND(AVG(REVIEW_SCORE), 2) AS SCORE
FROM REST_INFO AS RI, REST_REVIEW AS RR
WHERE RI.REST_ID = RR.REST_ID AND RI.ADDRESS LIKE "서울%"
GROUP BY REST_NAME
ORDER BY SCORE DESC, FAVORITES DESC